# Generated by Django 4.2.30 on 2026-09-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('finalized', 'Finalized')], default='open', max_length=10)),
                ('reminder_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_window_hours', models.PositiveIntegerField(default=24)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chores_app.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'household')},
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='chores_app.chore')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='chores_app.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='chores_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_chores', to='chores_app.member'),
        ),
        migrations.AddField(
            model_name='chore',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chores', to='chores_app.member'),
        ),
        migrations.AddField(
            model_name='chore',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores_app.household'),
        ),
    ]
